name: Verify API

on:
  pull_request:
    branches:
      - main
    paths:
      - "database/**"
      - "server/**"
      - "test/api/**"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start docker compose
        run: docker compose --profile dev up -d --wait && sleep 30
      - name: Test
        run:  npm i --prefix ./test/api && (npm test --prefix ./test/api&)
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: TestOutput
          path: ./test/api/html-report