name: Verify API

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Start docker compose
        run: docker compose -f ./billing-giants/docker-compose.yml --profile dev up -d --wait && sleep 30
      - name: Test
        run:  npm i --prefix ./api && (npm test --prefix ./api&)
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: TestOutput
          path: ./api/html-report